name: Deploy omemoji.com
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API
        run: HOOK=${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOKS }}
        run: curl -X POST "$HOOK"